### ISSUE TITLE
Exposed variables

### ISSUE THREAD

**Issue by m-azra3l** [HAPPYS1NGH/account-abstraction#8]
You exposed private values in the config.json file, consider using a js file(config.js). This way you can save your private values in an .env 
example:

 const config = {
  rpcUrl: process.env.RPC_URL,
  signingKey: process.env.SIGNING_KEY,
  entryPoint: "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789",
  simpleAccountFactory: "0x9406Cc6185a346906296840746125a0E44976454",
  paymaster: {
    rpcUrl: process.env.PAYMASTER_RPC_URL,
    context: { type: "payg" },
  },
};

module.exports = config; 

Then you can ` import { config } from './config'; `  anywhere you want to use the config file.

**Comment by HAPPYS1NGH** [comment]
The private key is stored on the browser in local storage and this was the template which was used initially.
The private key is generated as soon as a person opens the website for the first time.

The issue is that I need to have a more secure way of storing a private key on the browser.

**Comment by m-azra3l** [comment]
I understand that part, I am talking about your config.json. I thought the signingKey is a wallet private key, check through your project folder.

**Comment by HAPPYS1NGH** [comment]
Yes, I did not configured it after initial commit.
It is nothing but a boiler plate template.
